# NAME: Template Shadowrocket
# AUTHOR: KempeR1t
# REPO: https://github.com/KempeR1t/Shadowrocket-config
# UPDATED: 2025-09-29

[General]
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, localhost, *.local, captive.apple.com, 87.121.86.245/32
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 239.255.255.250/32, 255.255.255.255/32, 87.121.86.245/32
dns-server = https://1.1.1.1/dns-query, https://1.0.0.1/dns-query
fallback-dns-server = system
hijack-dns = :53
ipv6 = false
prefer-ipv6 = false
dns-fallback-system = true
dns-direct-system = true
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = false
always-real-ip = *
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/KempeR1t/Shadowrocket-config/refs/heads/main/kemper1t-shadowrocket-work.conf

[Rule]
DOMAIN-SUFFIX,yandex.ru,DIRECT
DOMAIN-SUFFIX,yandex.net,DIRECT
DOMAIN-SUFFIX,yandex-team.ru,DIRECT
DOMAIN-SUFFIX,yanet.org,DIRECT
DOMAIN,proxy-check.sec.yandex.net,DIRECT
DOMAIN,ovpn.net.yandex.net,DIRECT

DOMAIN,newlife.kemper1t.ru,DIRECT
DOMAIN,newstory.kemper1t.ru,DIRECT
IP-CIDR,87.121.86.245/32,DIRECT,no-resolve

IP-CIDR,5.45.192.0/18,DIRECT,no-resolve
IP-CIDR,5.255.192.0/18,DIRECT,no-resolve
IP-CIDR,10.208.0.0/12,DIRECT,no-resolve
IP-CIDR,37.9.64.0/18,DIRECT,no-resolve
IP-CIDR,37.140.128.0/18,DIRECT,no-resolve
IP-CIDR,77.88.0.0/18,DIRECT,no-resolve
IP-CIDR,84.252.160.0/19,DIRECT,no-resolve
IP-CIDR,87.250.224.0/19,DIRECT,no-resolve
IP-CIDR,93.158.128.0/18,DIRECT,no-resolve
IP-CIDR,95.108.128.0/17,DIRECT,no-resolve
IP-CIDR,100.43.64.0/19,DIRECT,no-resolve
IP-CIDR,141.8.128.0/18,DIRECT,no-resolve
IP-CIDR,172.24.0.0/13,DIRECT,no-resolve
IP-CIDR,178.154.128.0/19,DIRECT,no-resolve
IP-CIDR,199.21.96.0/22,DIRECT,no-resolve
IP-CIDR,199.36.240.0/22,DIRECT,no-resolve
IP-CIDR,213.180.192.0/19,DIRECT,no-resolve
IP-CIDR,213.180.205.1/32,DIRECT,no-resolve

DOMAIN,2ip.io,PROXY
DOMAIN,google.com,PROXY
DOMAIN,cloudflare.com,PROXY

FINAL,DIRECT
